// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET106_Demo_API.Data;

#nullable disable

namespace NET106_Demo_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230720013501_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NET106_Demo_Shared.FootballPlayer", b =>
                {
                    b.Property<int>("FootballPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FootballPlayerId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("FootballPlayerId");

                    b.ToTable("FootballPlayers");

                    b.HasData(
                        new
                        {
                            FootballPlayerId = 1,
                            DateOfBirth = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyen Quang Huy",
                            Nationality = "Vietnam",
                            Photo = "images/nophoto.png",
                            PositionId = 1
                        });
                });

            modelBuilder.Entity("NET106_Demo_Shared.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("PosiotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            PosiotionName = "FW"
                        },
                        new
                        {
                            PositionId = 2,
                            PosiotionName = "MF"
                        },
                        new
                        {
                            PositionId = 3,
                            PosiotionName = "DF"
                        },
                        new
                        {
                            PositionId = 4,
                            PosiotionName = "GK"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
